name: Jest - SonarCloud

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unittest:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '16.13.0'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Install Vue CLI
        run: npm install -g @vue/cli

      - name: test unit
        run: yarn test:unit

      - uses: actions/upload-artifact@v2
        with:
          name: my-unit-test
          path: |
            tests/unit/coverage/*.info
            tests/unit/report/*.xml 


  sonarcloud:
    name: Analyze with SonarCloud
    needs: [unittest]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: yarn

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.VUE_TYPESCRIPT_EXAMPLE_SONAR_TOKEN }}
